import * as fs from "fs";
import * as path from "path";
import moment from "moment";
import { faker } from "@faker-js/faker";
import { BatchFileSummary, BatchPaymentRecord } from "../src/modules/payments/interfaces/BatchPayment";

/**
 * Builds and parses batch payment XML files for the Batch Payments feature.
 *
 * SCHEMA NOTE: the element names/structure used here are a PLACEHOLDER,
 * assumed from common bank batch payment file formats. They must be
 * verified/updated once a real sample XML file is provided by the business:
 *   <BatchPayment>
 *     <BatchReference>...</BatchReference>
 *     <DebitAccount>...</DebitAccount>
 *     <Payments>
 *       <Payment>
 *         <BeneficiaryName/> <BeneficiaryAccountNumber/> <BankName/> <BranchCode/>
 *         <PaymentMethod/> <Amount/> <PaymentReference/> <DebitAccountReference/> <PaymentDate/>
 *       </Payment>
 *     </Payments>
 *   </BatchPayment>
 * See apps/test/resources/batch-payments/valid-batch-payment-file.xml for a full example.
 *
 * Only parsing/building the flat structure above is supported - swap the
 * regex extraction below for a proper XML parser if the real schema is
 * nested/more complex.
 */
export default class BatchFileHelper {
    private static readonly OUTPUT_DIR = path.join(process.cwd(), "BatchPerfuploaded");

    /**
     * Generates a batch payment XML file containing `numberOfPayments` valid,
     * randomised payment rows for the given debit account, writes it to disk,
     * and returns the summary (expected values) to assert against the UI later.
     */
    static buildValidBatchXmlFile(debitAccount: string, numberOfPayments: number = 3): BatchFileSummary {
        const batchReference = `BATCH-AUTOMATION-${Math.floor(Math.random() * 90000) + 10000}`;
        const paymentDate = moment().add(1, "days").format("YYYY-MM-DD");

        const records: BatchPaymentRecord[] = [];
        for (let i = 0; i < numberOfPayments; i++) {
            const amount = faker.finance.amount({ min: 100, max: 5000, dec: 2 });
            records.push({
                rowNumber: i,
                beneficiaryName: `Automation Beneficiary ${i + 1}`,
                beneficiaryAccount: faker.finance.accountNumber(10),
                bank: "Investec",
                branchCode: "580105",
                paymentMethod: "EFT",
                amount,
                beneficiaryReference: `AutoBenRef${Math.floor(Math.random() * 9000) + 1000}`,
                debitAccRef: `AutoDebRef${Math.floor(Math.random() * 9000) + 1000}`,
                paymentDate,
            } as BatchPaymentRecord);
        }

        const paymentsXml = records
            .map(
                (record) => `    <Payment>
      <BeneficiaryName>${record.beneficiaryName}</BeneficiaryName>
      <BeneficiaryAccountNumber>${record.beneficiaryAccount}</BeneficiaryAccountNumber>
      <BankName>${record.bank}</BankName>
      <BranchCode>${record.branchCode}</BranchCode>
      <PaymentMethod>${record.paymentMethod}</PaymentMethod>
      <Amount>${record.amount}</Amount>
      <PaymentReference>${record.beneficiaryReference}</PaymentReference>
      <DebitAccountReference>${record.debitAccRef}</DebitAccountReference>
      <PaymentDate>${record.paymentDate}</PaymentDate>
    </Payment>`
            )
            .join("\n");

        const xml = `<?xml version="1.0" encoding="UTF-8"?>
<BatchPayment>
  <BatchReference>${batchReference}</BatchReference>
  <DebitAccount>${debitAccount}</DebitAccount>
  <Payments>
${paymentsXml}
  </Payments>
</BatchPayment>
`;

        if (!fs.existsSync(this.OUTPUT_DIR)) {
            fs.mkdirSync(this.OUTPUT_DIR, { recursive: true });
        }

        const fileName = `${batchReference}.xml`;
        const filePath = path.join(this.OUTPUT_DIR, fileName);
        fs.writeFileSync(filePath, xml, "utf-8");

        const totalAmount = records
            .reduce((sum, record) => sum + parseFloat(record.amount), 0)
            .toFixed(2);

        return {
            fileName,
            batchReference,
            debitAccount,
            totalPayments: records.length,
            totalAmount,
            records,
        };
    }

    /**
     * Returns the absolute path a previously built batch file was written to,
     * for handing to page.setInputFiles().
     */
    static getFilePath(fileName: string): string {
        return path.join(this.OUTPUT_DIR, fileName);
    }

    /**
     * Parses a batch payment XML file already on disk back into a
     * BatchFileSummary - useful when validating a file supplied by the
     * business (fixed sample) rather than one generated by buildValidBatchXmlFile.
     */
    static parseXmlFile(filePath: string): BatchFileSummary {
        const xml = fs.readFileSync(filePath, "utf-8");

        const batchReference = this.extractTag(xml, "BatchReference");
        const debitAccount = this.extractTag(xml, "DebitAccount") ?? "";

        const paymentBlocks = xml.match(/<Payment>[\s\S]*?<\/Payment>/g) ?? [];
        const records: BatchPaymentRecord[] = paymentBlocks.map((block, index) => ({
            rowNumber: index,
            beneficiaryName: this.extractTag(block, "BeneficiaryName") ?? "",
            beneficiaryAccount: this.extractTag(block, "BeneficiaryAccountNumber") ?? "",
            bank: this.extractTag(block, "BankName") ?? "",
            branchCode: this.extractTag(block, "BranchCode") ?? "",
            paymentMethod: this.extractTag(block, "PaymentMethod") ?? "",
            amount: this.extractTag(block, "Amount") ?? "0",
            beneficiaryReference: this.extractTag(block, "PaymentReference") ?? "",
            debitAccRef: this.extractTag(block, "DebitAccountReference") ?? "",
            paymentDate: this.extractTag(block, "PaymentDate") ?? "",
        } as BatchPaymentRecord));

        const totalAmount = records
            .reduce((sum, record) => sum + parseFloat(record.amount), 0)
            .toFixed(2);

        return {
            fileName: path.basename(filePath),
            batchReference,
            debitAccount,
            totalPayments: records.length,
            totalAmount,
            records,
        };
    }

    private static extractTag(xml: string, tagName: string): string | undefined {
        const match = xml.match(new RegExp(`<${tagName}>([\\s\\S]*?)<\\/${tagName}>`));
        return match ? match[1].trim() : undefined;
    }
}
